[project]
title = "All time JPMorgan Chase Stock Data 1980 - 2025"
version = "0.1.0"
port = 8501
slug = "ashmit-dev-jpmorgan-chase-stock-data-visualization"  # Required: Unique identifier for your project
entrypoint = "src/hello.py"    # Required: Main script to run when executing preswald run

[branding]
name = "All time JPMorgan Chase Stock Data 1980 - 2025"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#3535cc"

[data.jpm]
type = "csv"
path = "data/JPM_1940-01-01_2025-03-04.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"